include:
 # To fetch the latest template, use:
  - template: Terraform.latest.gitlab-ci.yml

# variables:
#  TF_STATE_NAME: default
#  TF_CACHE_KEY: default

gcp-auth:
  image: google/cloud-sdk:slim
  script:
    - echo ${CI_JOB_JWT_V2} > .ci_job_jwt_file
    - gcloud iam workload-identity-pools create-cred-config ${GCP_WORKLOAD_IDENTITY_PROVIDER}
      --service-account="${GCP_SERVICE_ACCOUNT}"
      --output-file=.gcp_temp_cred.json
      --credential-source-file=.ci_job_jwt_file
    - gcloud auth login --cred-file=`pwd`/.gcp_temp_cred.json
    - gcloud auth list

gcp-sts:
  image: dwdraju/alpine-curl-jq
  script:
    - chmod u+x ./run_gcp_sts.sh
    - ./run_gcp_sts.sh

validate:
  extends: .terraform:validate
