on:
  push:
    branches:
      - deploy

jobs:
  initialize:
    name: Initialize
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Auth to GCP
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ secrets.SA }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Test command - gcloud info
      run: 'gcloud info'

    - name: Terraform init
      run: |
        terraform init -upgrade

    - name: Terraform validate
      run: |
        terraform validate

    - name: Terraform plan
      run: |
        terraform plan

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: initialize
    permissions:
      contents: 'read'
      id-token: 'write'
    environment:
        name: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Auth to GCP
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.SA }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Terraform init
        run: |
          terraform init -upgrade

      - name: Terraform apply
        run: |
          terraform apply -auto-approve
